version: '1.0.{build}'

image: ubuntu

assembly_info:
  patch: false

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

pull_requests:
  do_not_increment_build_number: true

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - dotnet restore -v Minimal %APPVEYOR_BUILD_FOLDER%\src\AniSync\AniSync.csproj

build_script:
  - dotnet publish -c Release -r ubuntu.16.04-x64 %APPVEYOR_BUILD_FOLDER%\src\AniSync\AniSync.csproj -o %APPVEYOR_BUILD_FOLDER%\_build
  - docker build -t anisync .

only_commits:
  files:
    - src/
    - appveyor.yml