version: '1.0.{build}'

image: ubuntu

stack: node 10.9.0

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - sh: chmod +x ./build.sh

build_script:
  - sh: ./build.sh

only_commits:
  files:
    - src/
    - appveyor.yml
    - build.cake